### ISSUE TITLE
Need Help Looping thru BoxScores

### ISSUE THREAD

**Issue by luzer** [jtpavlock/nbapy#2]
i am trying just to get 2nd dataframe in the return, and loop thru all games

```
from nbapy import game
game_id = '0021900017'
stats = game.BoxScore(game_id).players_stats()
```

**Comment by jtpavlock** [comment]
All responses are returned as pandas dataframes. That's my fault for not documenting that, sorry!

I added a quick usage example to [the wiki](https://github.com/jtpavlock/nbapy/wiki) that should help.

Edit: rereading your question, I'm not entirely sure what you're trying to do. You are specifying a single game via "game_id" but are trying to loop through multiple games?

**Comment by luzer** [comment]
this worked, thanks!
yes- i am trying to loop thru all games in the entire DB and append a DF.  but i want to include the player's names

**Comment by jtpavlock** [comment]
It may not be exactly what you're looking for, but I just added a [scoreboard endpoint](https://github.com/jtpavlock/nbapy/blob/master/docs/scoreboard/Scoreboard.ipynb) that will allow you to see all game_ids for a given day which you can then loop through using the game endpoint
