### ISSUE TITLE
New to Python but have question for you

### ISSUE THREAD

**Issue by leighrobertson512** [jtpavlock/nbapy#6]
Hey man thanks so much for sharing this repo! It's been great for me doing some exploratory analysis. I am running into a timeout issue though which I think might be a function of the NBA stats side. I am trying to get the player information for all NBA players. Your documentation allowed me to get the information for an individual player very easily. I am looping through to get for all players and am consistently running into a timeout issue. Do you know if the NBA stats prohibits this type of behavior? Or could I change the timeout setting myself?

summary = Summary(1629027)
summary.info()

**Comment by jtpavlock** [comment]
Hey @leighrobertson512 ! Thanks for the kind words. Can I ask what version you're on?

**Comment by leighrobertson512** [comment]
Version of python? I am using 3.7. As for the repo I pulled the latest version about 6 days ago when I started working on this.

**Comment by jtpavlock** [comment]
I meant of nbapy, sorry. I recently added some rate limiting to the api calls to try and help with timeout issues, so I'd try upgrading to the newest version and seeing if that helps at all.
